name: infra-ci

on:
  push:
    branches: [ main ]
    paths:
      - 'terraform/**'
      - 'src/count_function/**'
      - 'src/tests/**'
      - '.github/workflows/infra-ci.yml'
  workflow_dispatch: {}

permissions:
  contents: read
  id-token: write

env:
  PYTHON_VERSION: "3.12"
  AWS_REGION: "us-east-1"
  TF_DIR: "terraform"

concurrency:
  group: infra-ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dev deps
        run: |
          python -m pip install --upgrade pip
          pip install -r src/tests/requirements-dev.txt

      - name: Pytest
        env:
          AWS_DEFAULT_REGION: ${{ env.AWS_REGION }}
        run: pytest -q
  
  gate:
    needs: test
    uses: patrick-heese/aws-iac-quality-gate/.github/workflows/reusable-iac-gate.yml@v1
    with:
      iac_tool: terraform
      working_directory: terraform
      aws_region: us-east-1
      aws_role_arn: arn:aws:iam::493233983993:role/GitHubOIDC-Infra
      apply: true
